### ISSUE TITLE
New site doesn't work on Edge on a mobile device

### ISSUE THREAD

**Issue by mccrispy** [on3iro/aeons-end-randomizer#180] opened 2019-10-06 23:12 UTC
Yes, I know MS has stopped support for mobile 😉 but I used to use the previous version on my Windows Phone and now I can't. That makes me sad 😢 'cos I'll have to use a different randomiser App and I liked this one best.

By "doesn't work" I mean that it displays a completely blank page - no menu, no text, nothing

**Comment by on3iro** [comment] 2019-10-07 07:32
@mccrispy hm, that's sad. I suppose you have a windows phone? Maybe you could try to install another browser like opera mini.
I will have a look at this issue as soon as I have some spare time (we are currently working on two other main features - all in our free time ;D ). I can't promise you that there will be an easy fix, though.

**Comment by on3iro** [comment] 2019-10-07 07:40
@mccrispy hm, ok I had a quick look into this via browserstack. I could reproduce the errorm but unfortunately this is extremely hard to debug.

Could you try out a different mobile browser and let me know, if that fixes the issue? As far as I know Windows Phones are currently the only mobile devices where our randomizer does not work on.

I will still definitely check out if there's something I could do to fix the issue, but it will probably take some time :(

**Comment by on3iro** [comment] 2019-10-07 08:43
@mccrispy another question: could you pinpoint since when it does not work anymore? It has probably to do with the client side routing we implemented recently.
However if this is the issue (which is likely), we probably wont be able to fix it, as the new routing is pretty much ingrained into our architecture.

**Comment by on3iro** [comment] 2019-10-07 09:50
@mccrispy you might be in luck, there is one change we wanted to make in the near future, that might actually fix the issue (no promises, yet ;D). I will look into this and let you know, if it will work.

**Comment by on3iro** [comment] 2019-10-07 12:00
@mccrispy ok, I quickly started drafting the feature I wanted to do anyway and unfortunately it looks like it wont fix your issue. On the other hand I am no longer sure that the routing is the issue here. I will have a deeper look into this, maybe I'll find the culprit somewhere else.

**Comment by on3iro** [comment] 2019-10-07 12:12
@mccrispy oh man, I am at work, not doing what I am supposed to 😅 instead I am fixing windows phone errors.

Buuuuut, good news: I think I found the issue and I am probably able to resolve it. 🎉 🎉 🎉 
I'll try to implement a fix tonight and will let you know when its live inside this issue here :)

**Comment by on3iro** [comment] 2019-10-07 12:44
@mccrispy could you please do me a favor and check out this link with your windows phone?
https://5d9b32d3d64adc95de11d0a9--aer.netlify.com/nemesis

This is a staging system already containing the fixes. If everything works fine for you I will deploy the release to the live system, so you can actually use it ;)

**Comment by mccrispy** [comment] 2019-10-07 14:37
Sorry that you've been working away and I've not responded! Let me answer the questions that you asked:
Q: Could you try out a different mobile browser
A: I can look into it, but it's really not my preferred option (tbh, I'd rather abandon the randomiser than use a different browser)

Q: Could you pinpoint since when it does not work anymore?
A: Not to a narrow window. It worked on the old URL and doesn't work on the new URL but it's been a couple of months since I used the randomiser (is my guess)

Q: Could you please do me a favor and check out this link with your windows phone?
A: I did that and it worked. At least for a while. Then my phone crashed while I had the menu window open! (I had left it open for a minute or so while I drafted this reply). However, it seems OK after the reboot - it seems to spontaneously refresh the page every now and then but that doesn't seem to change the state of the App, so it looks as though we're good to go! THANKS

**Comment by on3iro** [comment] 2019-10-07 17:06
@mccrispy nice - thanks for the elaborate answer. I could not reproduce the page refresh issue, so I will deploy the app to live, now.

Please let me know if you still have got any issues :)

**Comment by on3iro** [comment] 2019-10-07 17:09
Fix released with v1.10.0

**Closed by on3iro** 2019-10-07 17:09 UTC
Labels: bug

**Comment by mccrispy** [comment] 2019-10-07 20:35
I seem to have 1.10.0 running and everything looks OK at the moment. Great job, thanks!
